[build]
  outDir = "dist"
  assetsDir = "assets"
  sourcemap = "true"
  rollupOptions = { 
    input: "./src/main.tsx",
    output: {
      entryFileNames: 'assets/[name]-[hash].js',
      chunkFileNames: 'assets/[name]-[hash].js',
      assetFileNames: 'assets/[name]-[hash][extname]'
    }
  }

[server]
  host = "0.0.0.0"
  port = 3000
  strictPort = true

[public]
  base = "/"

[build.optimizeDeps]
  include = [
    "react",
    "react-dom"
  ]

[build.css]
  postcss = {
    plugins = [
      require('autoprefixer')
    ]
  }
